all:
  hosts:
    mgmt-win:
      ansible_host: MGMT01.domain.local
      ansible_connection: ssh
      ansible_shell_type: powershell
      ansible_port: 23456
      ansible_user: "svcGitlabDNS@domain.local"
